coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: error
    patch:
      default:
        target: 80%
        threshold: 1%
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 80%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: backend  #fill in your own flag name
      paths:
        - backend  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%
    - name: frontend #fill in your own flag name
      paths:
        - frontend  #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - type: project
          target: 20%
        - type: patch
          target: 100%