CREATE TABLE IF NOT EXISTS booking (
    id SERIAL PRIMARY KEY,
    user_email VARCHAR(255) NOT NULL,
    slot TIMESTAMP NOT NULL,
    booking_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
);

